services:

  Predis\Client: '@snc_redis.default'
  Predis\ClientInterface: '@Predis\Client'

  AvailabilityBundle\Service\RedisService:
    class: AvailabilityBundle\Service\RedisService
    arguments:
      - '@Predis\ClientInterface'
    public: public

  AvailabilityBundle\Service\AvailabilityService:
    class: AvailabilityBundle\Service\AvailabilityService
    arguments:
      - '@AvailabilityBundle\Service\RedisService'
    public: public

  AvailabilityBundle\Service\RedisInterface:
    alias: '@AvailabilityBundle\Service\RedisService'
    public: true

  AvailabilityBundle\Service\AvailabilityInterface:
    alias: '@AvailabilityBundle\Service\AvailabilityService'
    public: true
